# docker-compose.yml
services:
  data_collector:
    build:
      context: ./services/data_collector
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - "5100:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  ml_model:
    build:
      context: ./services/ml_model
      dockerfile: Dockerfile
    environment:
      - PORT=6000
    ports:
      - "6000:6000"
    depends_on:
      - data_collector
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  sec_manager:
    build:
      context: ./services/sec_manager
      dockerfile: Dockerfile
    environment:
      - PORT=9000
    ports:
      - "9000:9000"
    depends_on:
      - ml_model
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  fin_dash:
    build:
      context: ./services/fin_dash
      dockerfile: Dockerfile
    environment:
      - PORT=7000
    ports:
      - "7100:7000"
    depends_on:
      - sec_manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 5