# docker‑compose.yml  ── Compose V2 syntax (no “version:” key)

services:
  # ────────────────────────────────────────── data‑collector ──
  data_collector:
    build: ./services/data_collector
    container_name: data_collector
    restart: unless-stopped
    volumes:
      - ./services/data_collector:/app           # service source
      - ./tests/data_collector_tests:/app/tests  # make tests visible in the image
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "6000:6000"                              # host:container (matches tests)

  # ────────────────────────────────────────────────── ml‑model ──
  ml_model:
    build: ./services/ml_model
    container_name: ml_model
    restart: unless-stopped
    volumes:
      - ./services/ml_model:/app
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "5200:8000"

  # ────────────────────────────────────────────────── fin‑dash ──
  fin_dash:
    build: ./services/fin_dash
    container_name: fin_dash
    restart: unless-stopped
    volumes:
      - ./services/fin_dash:/app
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "7100:8050"

  # ─────────────────────────────────────────────── sec‑manager ──
  sec_manager:
    build: ./services/sec_manager
    container_name: sec_manager
    restart: unless-stopped
    volumes:
      - ./services/sec_manager:/app
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "5000:8000"