# docker‑compose.yml   (root of repo)
#
# single network shared by every service
# explicit environment mappings (not a list!)
# each service exposes the port the test‑suite expects

services:
  data_collector:
    build:
      context: ./services/data_collector
    container_name: data_collector
    ports:
      - "6000:6000"            # tests hit http://localhost:6000
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:                   # mount only this test folder when you run pytest
      - ./tests/data_collector_tests:/app/tests
    entrypoint: ["/entrypoint.sh"]

  ml_model:
    build:
      context: ./services/ml_model
    container_name: ml_model
    ports:
      - "5100:5100"
    environment:
      PYTHONUNBUFFERED: "1"

  fin_dash:
    build:
      context: ./services/fin_dash
    container_name: fin_dash
    ports:
      - "7100:7100"
    environment:
      PYTHONUNBUFFERED: "1"

  sec_manager:
    build:
      context: ./services/sec_manager
    container_name: sec_manager
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"

networks:
  default:
    driver: bridge