version: "3.9"

services:
  # -------------------- DATA COLLECTOR --------------------
  data_collector:
    build: ./services/data_collector
    container_name: data_collector
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./services/data_collector:/app
    ports:
      - "5100:8000"

  # -------------------- ML MODEL ---------------------------
  ml_model:
    build: ./services/ml_model
    container_name: ml_model
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./services/ml_model:/app
    ports:
      - "5200:8000"

  # -------------------- SEC MANAGER ------------------------
  sec_manager:
    build: ./services/sec_manager
    container_name: sec_manager
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./services/sec_manager:/app
    ports:
      - "5000:8000"

  # -------------------- FIN DASH ---------------------------
  fin_dash:
    build: ./services/fin_dash
    container_name: fin_dash
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./services/fin_dash:/app
    ports:
      - "7100:8050"

networks:
  default:
    driver: bridge